language: minimal
services: docker
install:
  - npm --version
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed fandresfonsecao/udagram-api-feed:v1 
  - docker tag udagram-api-user fandresfonsecao/udagram-api-user:v1
  - docker tag udagram-frontend fandresfonsecao/udagram-frontend:v1
  - docker tag udagram-reverseproxy fandresfonsecao/udagram-reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fandresfonsecao/udagram-api-feed:v1
  - docker push fandresfonsecao/udagram-api-user:v1
  - docker push fandresfonsecao/udagram-frontend:v1
  - docker push fandresfonsecao/udagram-reverseproxy:v1