dist: focal
language: node_js
node_js:
  - 19
services:
  - docker
install:
  - echo "nothing needs to be installed"
before_script:
  - echo "no tests"
script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed fandresfonsecao/udagram-api-feed:v1 
  - docker tag udagram-api-user fandresfonsecao/udagram-api-user:v1
  - docker tag udagram-frontend fandresfonsecao/udagram-frontend:v1
  - docker tag udagram-reverseproxy fandresfonsecao/udagram-reverseproxy:v1
  - echo "*****Images*****"
  - docker images
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fandresfonsecao/udagram-api-feed:v1
  - docker push fandresfonsecao/udagram-api-user:v1
  - docker push fandresfonsecao/udagram-frontend:v1
  - docker push fandresfonsecao/udagram-reverseproxy:v1