apiVersion: v1
data:
  aws_access_key_id: UVV0SlFUVk1ORE5OVjAwMVJUZFdSa05DVGs0PQ==
  aws_secret_access_key: TURVd04wRlNkREpvWkdkakwxTXpTelpMTUdSd1ZVVlFUamw0UjI5NFVtTktkREJyUzBWT1ZnPT0=
kind: Secret
metadata:
  creationTimestamp: null
  name: aws
type: string