apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: udagram-frontend
  name: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udagram-frontend
    spec:
      containers:
      - image: fandresfonsecao/udagram-frontend:v2
        name: udagram-frontend
        imagePullPolicy: Always
        resources:
         requests: 
          cpu: "500m"
         limits:
          cpu: "200m"
        ports:
        - containerPort: 80
        resources: {}
status: {}